provider: CICS
programInterface: CHANNEL
language: COBOL
connectionRef: cicsConn
program: RBKZCAPI
ccsid: 037
providerPrefix: RBK
providerExtension: cpy
defaultCharacterMaxLength: 50
defaultFractionDigits: 2
